---
- set_fact:
    manageiq_conversion_host_resource_ems_ref: "{{ ansible_machine_id[:8] }}-{{ ansible_machine_id[8:12] }}-{{ ansible_machine_id[12:16] }}-{{ ansible_machine_id[16:20] }}-{{ ansible_machine_id[20:] }}"

- uri:
    url: "{{ manageiq_url }}/api/hosts/?expand=resources&attributes=ext_management_system&filter[]=name={{ inventory_hostname }}&filter[]=ext_management_system.name={{ manageiq_provider_name | regex_replace(' ', '%20') }}"
    user: "{{ manageiq_username }}"
    password: "{{ manageiq_password }}"
    method: GET
    validate_certs: false
  register: manageiq_get_conversion_host_resources_json

- block:
    - set_fact:
        manageiq_get_conversion_host_resource: "{{ manageiq_get_conversion_host_resources_json.json | json_query('resources[*]') | first }}"

    - set_fact:
        manageiq_post_conversion_host_resource:
          name: "{{ manageiq_get_conversion_host_resource.name }}"
          resource_id: "{{ manageiq_get_conversion_host_resource.id }}"
          resource_type: "Host"
          vddk_transport_supported: "{{ 'vddk' in v2v_transport_methods }}"
          ssh_transport_supported: "{{ 'ssh' in v2v_transport_methods }}"

    - set_fact:
        manageiq_post_conversion_host_resource_href: "{{ manageiq_get_conversion_host_resource.href }}"

  when:
    - "manageiq_get_conversion_host_resources_json.json.subcount != 0"
