---
- name: Create SSH private key file for VMware host
  copy:
    dest: "{{ ssh_config_path }}/{{ vmware_host }}"
    content: "{{ hostvars[vmware_host]['conversion_ssh_private_key'] }}"
    owner: "{{ ssh_config_owner }}"
    mode: 0600

- name: Add SSH config entry for VMware host
  blockinfile:
    path: "{{ ssh_config_path }}/config"
    block: |
      Host {{ vmware_host }}
        User {{ hostvars[vmware_host]['conversion_ssh_username'] | default('root') }}
        IdentityFile {{ ssh_config_path }}/{{ vmware_host }}
    create: yes
    owner: "{{ ssh_config_owner }}"
    mode: 0600
