---
- name: Create the repository file for nbdkit packages
  copy:
    dest: /etc/yum.repos.d/v2v-nbdkit.repo
    owner: root
    group: root
    mode: 0644
    content: |
      [{{ v2v_repo_rpms_name }}]
      name={{ v2v_repo_rpms_name }}
      baseurl={{ v2v_repo_rpms_url }}
      enabled=1
      gpgcheck=0

      [{{ v2v_repo_srpms_name }}]
      name={{ v2v_repo_srpms_name }}
      baseurl={{ v2v_repo_srpms_url }}
      enabled=1
      gpgcheck=0
  when:
    - "v2v_repo_rpms_name is defined"
    - "v2v_repo_rpms_url is defined"
    - "v2v_repo_srpms_name is defined"
    - "v2v_repo_srpms_url is defined"
